version: "3.9"
services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    ports:
      - '7880:7880'
      - '7881:7881'
      - '7882:7882/udp'
      - '8443:443'
    expose:
      - 7880
      - 7881
      - '7882/udp'
      - '50000-60000/udp'
      
  redis:
    image: redis:6-alpine
    command: redis-server /etc/redis.conf
    network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf
